# config.yaml

# dataset: "cube"                # Options: cube, grid, gas10, MNIST
# nearest_neighbors: 20          # k value for nearest neighbors
# acquisition_cost: 0.05         # Cost for each feature acquisition
# train_or_validation: "train"   # Options: train, valid
# num_instances: 2               # How many instances to perform the rollout on

dataset: "adni"                # Options: cube, grid, gas10, MNIST
nearest_neighbors: 10          # k value for nearest neighbors

# acquisition_cost: 0.0025         # XGB
# acquisition_cost: 0.01         # MLP sythetic

acquisition_cost: 0.01         # MLP adni
acquisition_cost: 0.0060         # MLP progressive

train_or_validation: "valid"   # Options: train, valid

num_instances: 200               # adni
# num_instances: 400               # synthetic